on:
  push:
    branches:
    - main
name: Publish docs
jobs:
  publishProjectDocs:
    name: Publish project documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-elixir@v1
      with:
        otp-version: 25.x
        elixir-version: 1.15.x
    - name: Generate docs
      uses: lee-dohm/generate-elixir-docs@v1
      with:
        tagVersionWithHash: true
      env:
        MIX_ENV: test
    - name: Publish docs
      uses: peaceiris/actions-gh-pages@v1.0.1
      env:
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./doc